### GET Suppliers top 2
GET http://localhost:4004/odata/v4/catalog/Suppliers?$top=2

### GET Products top 2
GET http://localhost:4004/odata/v4/catalog/Products?$top=2

### GET Products top 2
GET http://localhost:4004/odata/v4/catalog/Products?&$select=identifier,price

### POST a Product
POST http://localhost:4004/odata/v4/catalog/Products
Content-Type: application/json

{
    "ID":"a9fe4b01-ccd3-4369-821c-291a7552dffb"
} 


